config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import reverse
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views

urlpatterns = [
    #url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^$', RedirectView.as_view(url='/billing/pay', permanent=False), name="home"),
    url(r'^about$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('rink.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^billing/', include('billing.urls', namespace='billing')),
    url(r'^legal/', include('legal.urls', namespace='legal')),
    url(r'^organization/', include('league.urls', namespace='league')),
    url(r'^register/', include('registration.urls', namespace="register")),
    url(r'^registration/', include('registration.urls_admin', namespace='registration')),
    url(r'^roster/', include('roster.urls', namespace='roster')),
    url(r'^tickets/', include('tickets.urls', namespace='tickets')),
    url(r'^voting/', include('voting.urls', namespace='voting')),

    url(r'^robots.txt',
        TemplateView.as_view(template_name='robots.txt', content_type='text/plain'),
        name="robots_file")




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

rink/billing/urls.py
from django.urls import path

from . import views
from . import views_admin

app_name = 'billing'
urlpatterns = [
    path('admin', views_admin.BillingAdminView.as_view(), name="billing_admin"),
    path('admin/<int:pk>', views_admin.BillingAdminDetailView.as_view(), name="billing_admin_detail"),
    path('admin/<int:pk>/payment',
        views_admin.BillingAdminAddPaymentView.as_view(), name="billing_admin_add_payment"),
    path('admin/<int:pk>/refund', 
        views_admin.BillingAdminRefundPaymentView.as_view(), name="billing_admin_refund_payment"),
    path('admin/<int:pk>/edit', 
        views_admin.BillingAdminEditInvoiceView.as_view(), name="billing_admin_edit_invoice"),

    path('pay', views.PayView.as_view(), name="pay"),
    path('payments', views.PaymentHistoryView.as_view(), name="payment_history"),
    path('update-card', views.UpdateUserStripeCardView.as_view(), name="update_card"),

]

rink/league/urls.py
from django.urls import path

from . import views

app_name = 'league'
urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    
    path('<slug:organization_slug>/leagues/', views.LeagueAdminList.as_view(), name="league_list"),
    path('<slug:organization_slug>/league/', views.LeagueAdminCreate.as_view(), name="league_create"),
    path('<slug:organization_slug>/league/<slug:slug>', views.LeagueAdminUpdate.as_view(), name="league_update"),
    path('<slug:organization_slug>/permissions/', views.OrganizationPermissionsView.as_view(), name="organization_permissions"),
    path('<slug:organization_slug>/permission/', views.OrganizationPermissionsChange.as_view(), name="organization_permissions_create"),
    path('<slug:organization_slug>/permission/<int:user_id>', views.OrganizationPermissionsChange.as_view(), name="organization_permissions_update"),
    path('<slug:organization_slug>/create-user/', views.CreateUserView.as_view(), name="create_rink_user"),

    # League view switcher
    path('switch-leagues-view/<slug:league_slug>', views.SwitchLeagueView.as_view(), name="switch_league_view"),

    # Insurance Types Admin
    path('<slug:organization_slug>/league/<slug:slug>/insurance',
        views.LeagueInsuranceTypesListView.as_view(),
        name="insurance_list"),

    path('<slug:organization_slug>/league/<slug:slug>/insurance/<int:insurance_type_id>',
        views.LeagueInsuranceTypesChangeView.as_view(),
        name="insurance_change"),

    path('<slug:organization_slug>/league/<slug:slug>/insurance/new',
        views.LeagueInsuranceTypesCreateView.as_view(),
        name="insurance_create"),


    # Billing Groups Admin
    path('<slug:organization_slug>/league/<slug:slug>/billing-groups',
        views.LeagueBillingGroupsListView.as_view(),
        name="billing_groups_list"),

    path('<slug:organization_slug>/league/<slug:slug>/billing-groups/<int:billing_group_id>',
        views.LeagueBillingGroupsChangeView.as_view(),
        name="billing_groups_change"),

    path('<slug:organization_slug>/league/<slug:slug>/billing-groups/new',
        views.LeagueBillingGroupsCreateView.as_view(),
        name="billing_groups_create"),

    # User Tags
    path('<slug:organization_slug>/league/<slug:slug>/tags',
        views.LeagueTagsListView.as_view(),
        name="tags_list"),
]

rink/legal/urls.py
from django.urls import path

from . import views

app_name = 'legal'
urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    # Leage Admin Views
    path('admin/documents/', 
        views.LegalDocumentList.as_view(),
        name="admin_document_list"),

    path('admin/document/', 
        views.LegalDocumentCreateUpdate.as_view(),
        name="admin_document_create_update"),

    path('admin/document/<int:document_id>/', 
        views.LegalDocumentCreateUpdate.as_view(),
        name="admin_document_create_update"),

    path('admin/document/<int:document_id>/delete', 
        views.LegalDocumentDelete.as_view(),
        name="admin_document_delete"),


    # User Views
    path('signed-forms/', 
        views.UserLegalSignaturesListView.as_view(),
        name="signed_forms"),


    # Public Views
    path('<slug:league_slug>/<slug:document_slug>/',
        views.LegalDocumentPublicView.as_view(),
        name="view_legal_document"),

    path('<slug:league_slug>/event/<slug:event_slug>/',
        views.LegalDocumentEventView.as_view(),
        name="view_event_legal_documents"),
]

rink/users/urls.py
from django.urls import path

from . import views


app_name = 'users'
urlpatterns = [
    path('profile/', 
        views.UserProfileView.as_view(),
        name="profile"
    ),
]

rink/roster/models.py
from django.db import models

# Create your models here.

rink/billing/forms.py
from django import forms
from django.utils import timezone
from crispy_forms.helper import FormHelper

from .models import PAYMENT_PROCESSOR_CHOICES, Invoice


class UpdateStripeCardForm(forms.Form):
    stripe_token = forms.CharField(max_length=50)


class PayNowForm(forms.Form):
    invoice_id = forms.IntegerField()


class InvoiceFilterForm(forms.Form):
    # For Invoice Admin filtering form
    search = forms.CharField(max_length=200, label='', required=False)
    paid = forms.BooleanField(initial=True, required=False)
    unpaid = forms.BooleanField(initial=True, required=False)
    refunded = forms.BooleanField(initial=True, required=False)
    canceled = forms.BooleanField(initial=True, required=False)
    filtered = forms.BooleanField(initial=True, required=False, widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.fields['search'].widget.attrs.update({'placeholder': "Search #, Name, Email"})


class QuickPaymentForm(forms.Form):
    processor = forms.ChoiceField(choices=PAYMENT_PROCESSOR_CHOICES, required=True, initial='cash')
    amount = forms.DecimalField(min_value=0.00, decimal_places=2)
    transaction_id = forms.CharField(max_length=200, required=False)
    payment_date = forms.DateField(initial=timezone.now())


class QuickInvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = ['invoice_amount', 'description', 'status', 'invoice_date', 'due_date']


class QuickRefundForm(forms.Form):
    refund_amount = forms.DecimalField(min_value=0.00, decimal_places=2)
    refund_reason = forms.CharField(max_length=200, required=False)

rink/billing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views import View

from .forms import UpdateStripeCardForm, PayNowForm
from .models import UserStripeCard, Invoice, BillingPeriod
from league.models import League

from stripe.error import CardError


class PayView(LoginRequiredMixin, View):
    template_name = "billing/pay.html"

    def get(self, request):
        league = League.objects.get(pk=request.session['view_league'])
        try:
            user_stripe_card = UserStripeCard.objects.get(user=request.user, league=league)
        except UserStripeCard.DoesNotExist:
            user_stripe_card = None

        invoices = Invoice.objects.filter(
            user=request.user,
            league=league,
            status='unpaid',
        )

        future_invoices = BillingPeriod.objects.filter(
            event__league=league,
            event__billingsubscription__user=request.user,
            event__billingsubscription__status='active',
            invoice_date__gte=timezone.now(),
        )

        for invoice in future_invoices:
            invoice.invoice_amount = invoice.get_invoice_amount(user=request.user)

        return render(request, self.template_name, {
            'invoices': invoices,
            'future_invoices': future_invoices,
            'user_stripe_card': user_stripe_card,
            'current_time': timezone.now(),
        })

    def post(self, request):
        # I suppose we could show form errors here, but whatever
        league = League.objects.get(pk=request.session['view_league'])
        form = PayNowForm(data=request.POST)

        if form.is_valid():
            try:
                invoice = Invoice.objects.get(
                    pk=form.cleaned_data['invoice_id'],
                    user=request.user,
                    league=league,
                    status='unpaid',
                )
            except Invoice.DoesNotExist:
                return redirect('billing:pay')

            if invoice.invoice_amount == 0:
                invoice.pay()
                messages.success(request, "<strong>$0 Payment successful!</strong> Thanks.</p>")
                return redirect('billing:pay')

            try:
                user_stripe_card = UserStripeCard.objects.get(user=request.user, league=league)
            except UserStripeCard.DoesNotExist:
                messages.error(request, "You do not have a credit card saved. Please save a credit card before attempting to pay an invoice. Sorry. Thanks.")
                return redirect('billing:pay')

            try:
                user_stripe_card.charge(invoice=invoice)
                messages.success(request, "<strong>Payment successful!</strong> We emailed you a receipt. Thanks.</p>")
            except ValueError as e:
                messages.error(request, e)
                return redirect('billing:pay')
            except CardError as e:
                body = e.json_body
                err = body.get('error', {})
                messages.error(request, "<p>We were unable to charge your credit card.</p>\
                    <p>Reason: {}</p>\
                    <p>Please try again or contact us if you continue to have issues.</p>".format(
                    err.get('message')))

        return redirect('billing:pay')


class PaymentHistoryView(LoginRequiredMixin, View):
    template_name = "billing/payment_history.html"

    def get(self, request):
        invoices = Invoice.objects.filter(
            user=request.user,
            league=League.objects.get(pk=request.session['view_league']),
        ).exclude(status='unpaid')

        return render(request, self.template_name, {
            'invoices': invoices,
        })


class UpdateUserStripeCardView(LoginRequiredMixin, View):
    template_name = "billing/update_card.html"

    def get(self, request):
        try:
            user_stripe_card = UserStripeCard.objects.get(
                user=request.user,
                league=League.objects.get(pk=request.session['view_league']),
            )
        except UserStripeCard.DoesNotExist:
            user_stripe_card = None

        return render(request, self.template_name, {
            'user_stripe_card': user_stripe_card,
        })

    def post(self, request):
        form = UpdateStripeCardForm(data=request.POST)
        if form.is_valid():
            card_profile, created = UserStripeCard.objects.get_or_create(
                user=request.user,
                league=League.objects.get(pk=request.session['view_league']),
            )

        try:
            card_profile.update_from_token(form.cleaned_data['stripe_token'])
            #payment = card_profile.charge(invoice=invoice, send_receipt=False)
            messages.success(request, "Card on file has been updated. Thanks!")
        except CardError as e:
            body = e.json_body
            err = body.get('error', {})
            messages.error(request, "<p>We were unable to save your credit card.</p>\
                <p>Reason: {}</p>\
                <p>Please try again or contact us if you continue to have issues.</p>".format(
                err.get('message'))
            )
        return redirect('billing:update_card')

rink/tickets/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View

from league.models import League
from league.utils import send_email
from .models import TicketEvent, TicketPurchase
from .forms import TicketForm

import stripe




class TicketPurchaseView(View):
    def get(self, request, league_slug, event_slug):
        league = get_object_or_404(League, slug=league_slug)
        event = get_object_or_404(TicketEvent, slug=event_slug)

        return render(request, 'tickets/tickets.html', {
                'league_template': league,
                'league': league,
                'event': event,
            }
        )  

    def post(self, request, league_slug, event_slug):
        league = get_object_or_404(League, slug=league_slug)
        event = get_object_or_404(TicketEvent, slug=event_slug)

        form = TicketForm(request.POST)
        if form.is_valid():
            # charge token five bucks
            stripe.api_key = league.get_stripe_private_key()
            stripe.api_version = settings.STRIPE_API_VERSION

            try:
                customer = stripe.Customer.create(
                    description=form.cleaned_data.get('derby_name'),
                    name=form.cleaned_data.get('real_name'),
                    email=form.cleaned_data.get('email'),
                    source=form.cleaned_data.get('stripe_token'),
                )

                charge = stripe.Charge.create(
                    amount=500,
                    currency='usd',
                    description=event.name,
                    customer=customer,
                )
            except stripe.error.CardError as e:
                body = e.json_body
                error = body.get('error', {})
            except:
                error = "A generic error happened when trying to charge your card. Weird."
            else:
                ticket = TicketPurchase.objects.create(
                    event=event,
                    real_name=form.cleaned_data.get('real_name'),
                    derby_name=form.cleaned_data.get('derby_name'),
                    email=form.cleaned_data.get('email'),
                    transaction_id=charge.id,
                    amount=5.00,
                )

                send_email(
                    league=league,
                    to_email=form.cleaned_data.get('email'),
                    template="ticket",
                    context={
                        'ticket': ticket,
                        'event': event,
                    },
                )

                return redirect('tickets:ticket_purchase_done', league_slug=league_slug, event_slug=event_slug)
        else:
            error = form.errors

        return render(request, 'tickets/tickets.html', {
                'league_template': league,
                'league': league,
                'event': event,
                'error': error,
            }
        )  


class TicketPurchaseDoneView(View):
    def get(self, request, league_slug, event_slug):
        league = get_object_or_404(League, slug=league_slug)
        event = get_object_or_404(TicketEvent, slug=event_slug)

        return render(request, 'tickets/done.html', {
                'league_template': league,
                'league': league,
                'event': event,
            }
        )  

rink/templates/billing/billing_admin.html
{% extends 'base.html' %}
{% load django_tables2 %}
{% load crispy_forms_tags %}

{% block title %}Billing Manager{% endblock %}


{% block css %}
<style type="text/css">
.form-check, .filter-button { margin-left: 10px; }
.filter-form { font-size: smaller; }
</style>
{% endblock %}



{% block content %}

<h4>Invoices</h4>

{% if filter_form %}
    <fieldset>
        <legend>Filter Invoices</legend>
        <form action="" method="get" class="form form-inline filter-form">
            
            {% crispy filter_form %}
            <input type="submit" class="btn btn-primary btn-sm filter-button" value="Filter">
        </form>
    </fieldset>
{% endif %}

{% render_table table %}

{% endblock %}

rink/templates/billing/billing_admin_detail.html
{% extends 'base.html' %}
{% load django_tables2 %}
{% load crispy_forms_tags %}

{% block title %}Invoice #{{ invoice.pk }} - {{ user }}{% endblock %}


{% block css %}

{% endblock %}



{% block content %}

<h4>Invoice #{{ invoice.pk }} <button type="button" class="btn disabled btn-sm btn-outline-{{ invoice.status_class }} text-uppercase">{{ invoice.status }}</button></h4>

{% include 'utils/messages.html' %}

<div class="container">
    <div class="row">
        <div class="col-sm">
            <fieldset>
                <legend>Invoiced To</legend>
                <strong>{{user }}</strong><br>
                <a href="mailto:{{ user.email }}">{{ user.email }}</a><br>
                <br>
                <a href="#"><button type="button" class="btn btn-primary">View User</button></a>
            </fieldset>
        </div>
        <div class="col-sm">
            <fieldset>
                <legend>Invoice Details</legend>
                <p><strong>Description:</strong> {{ invoice.description }} <a href="#">(view event)</a><br></p>
                
                <strong>Status:</strong> <button type="button" class="btn disabled btn-sm btn-outline-{{ invoice.status_class }} text-uppercase">{{ invoice.status }}</button><br>
                <strong>Amount:</strong> ${{ invoice.invoice_amount }}<br>
                <br>
                <strong>Invoice Date:</strong> {{ invoice.invoice_date|date:"n/j/Y" }}<br>
                <strong>Due Date:</strong> {{ invoice.due_date|date:"n/j/Y" }}<br>
                <strong>Paid Date:</strong> {{ invoice.paid_date|date:"n/j/Y" }}<br>
                <br>

                {% if not invoice.payment %}
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addPaymentModal">Add Payment</button>
                {% endif %}
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editInvoiceModal">Edit Invoice</button>
            </fieldset>
        </div>
        {% if invoice.payment %}
        <div class="col-sm">
            <fieldset>
                <legend>Payment Details</legend>
            
                <strong>Amount:</strong> ${{ payment.amount }}<br><br>
                <strong>Card:</strong> {{ payment.get_card }}<br>
                <strong>Paid by:</strong> {{ payment.processor }} {{ payment.transaction_id }}<br>
                <strong>Date:</strong> {{ payment.payment_date|date:"n/j/Y" }}<br>
                <br>

                {% if invoice.payment.is_refunded %}
                <strong>Refund Amount:</strong> ${{ payment.refund_amount }}<br>
                <strong>Refund Date:</strong> {{ payment.refund_date|date:"n/j/Y" }}<br>
                <strong>Refund Reason:</strong> {{ payment.refund_reason }}<br>
                <br>
                {% endif %}
                
                {% if not invoice.payment.is_refunded %}
                <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#sendRefundModal">Refund</button>
                {% endif %}
            </fieldset>
        </div>
        {% endif %}
    </div>
</div>

{% if not invoice.payment %}
<div class="modal fade" id="addPaymentModal" tabindex="-1" role="dialog" aria-labelledby="addPaymentLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form id="addPaymentForm" action="{% url 'billing:billing_admin_add_payment' pk=invoice.pk %}" method="post" class="form">
      <div class="modal-header">
        <h5 class="modal-title" id="addPaymentLabel">Add Payment - Invoice #{{ invoice.pk }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% csrf_token %}
        {% crispy payment_form %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input class="btn btn-success" type="submit" value="Add Payment" onclick="$(this).prop('disabled', 'disabled').val('Saving...');$('#addPaymentForm').submit();">
      </div>
      </form>
    </div>
  </div>
</div>
{% endif %}


<div class="modal fade" id="editInvoiceModal" tabindex="-1" role="dialog" aria-labelledby="editInvoiceLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form id="editInvoiceForm" action="{% url 'billing:billing_admin_edit_invoice' pk=invoice.pk %}" method="post" class="form">
      <div class="modal-header">
        <h5 class="modal-title" id="editInvoiceLabel">Edit Invoice - Invoice #{{ invoice.pk }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% csrf_token %}
        {% crispy invoice_form %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input class="btn btn-primary" type="submit" value="Edit Invoice" onclick="$(this).prop('disabled', 'disabled').val('Saving...');$('#editInvoiceForm').submit();">
      </div>
      </form>
    </div>
  </div>
</div>

{% if invoice.payment and not invoice.payment.is_refunded %}
<div class="modal fade" id="sendRefundModal" tabindex="-1" role="dialog" aria-labelledby="sendRefundLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form id="sendRefundForm"  action="{% url 'billing:billing_admin_refund_payment' pk=invoice.pk %}" method="post" class="form">
      <div class="modal-header">
        <h5 class="modal-title" id="sendRefundLabel">Refund Payment - Invoice #{{ invoice.pk }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% csrf_token %}
        {% crispy refund_form %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input class="btn btn-warning" type="submit" value="Refund Payment" onclick="$(this).prop('disabled', 'disabled').val('Saving...');$('#sendRefundForm').submit();">
      </div>
      </form>
    </div>
  </div>
</div>
{% endif %}

{% endblock %}

rink/templates/billing/pay.html
{% extends 'base.html' %}

{% block title %}Pay Dues{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3">

<h4>Pay Dues</h4>

{% include 'utils/messages.html' %}

<p class="mt-4">
    <strong>Credit card on file:</strong>
    {% if user_stripe_card %}
        {{ user_stripe_card }}
    {% else %}
         None
    {% endif %}
</p>
<p class="text-muted small">This card is used to charge for dues and invoices. <a href="{% url 'billing:update_card' %}">Need to update your credit card?</a> </p>


{% if invoices %}
    <div class="list-group mb-4 mt-4">
    {% for invoice in invoices %}
      <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">${{ invoice.invoice_amount }} / {{ invoice.status|upper }}</h5>
          <small>Invoice #{{ invoice.pk }}<br>{{ invoice.invoice_date }}</small>
        </div>
        <p class="mb-1">{{ invoice.description }}</p>
        <small>
            {% if current_time > invoice.due_date %}
            <strong>Payment was due on {{ invoice.due_date }}.</strong> Automatic payment failed.
            {% else %}
            <strong>Payment is due on {{ invoice.due_date }}.</strong>
            <br><strong>Your card will be automatically charged on this date</strong> or you can click the <i>Pay Now</i> button below.
            <form method="post" action="{% url 'billing:pay' %}" id="payment-form{{ invoice.pk }}">
                {% csrf_token %}
                <input type="hidden" name="invoice_id" value="{{ invoice.pk }}"/>
                <div class="mt-2"> 
                    <input type="submit" value="Pay Now" class="btn btn-primary button white" id="submit-id-submit" onclick="$(this).val('Please wait...').prop('disabled', 'disabled');$('#payment-form{{ invoice.pk }}').submit();" />
                </div>
            </form>                        
            {% endif %}
        </small>
      </a>                    
    {% endfor %}
    </div>
{% else %}
    <p><strong><mark>You have no unpaid invoices.</mark></strong></p>
    <p><a class="small" href="{% url 'billing:payment_history' %}">View your payment history here.</a></p>
{% endif %}

{% if future_invoices %}
<hr>
<p><strong>Upcoming Invoices</strong></p>
<p class="small text-muted">These are invoices that will be billed at a future date.</p>

    <div class="list-group">
    {% for invoice in future_invoices %}
      <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">${{ invoice.invoice_amount }}</h5>
          <small>{{ invoice.invoice_date }}</small>
        </div>
        <p class="mb-1">{{ invoice.name }}</p>
        <small>
            Invoice will be generated on {{ invoice.invoice_date}}.<br>
            Payment will be collected on {{ invoice.due_date }}.
        </small>
      </a>                    
    {% endfor %}
    </div>

{% endif %}

    </div>
</div>
{% endblock %}

rink/templates/billing/payment_history.html
{% extends 'base.html' %}

{% block title %}Payment History{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3">

<h4>Payments</h4>

{% if invoices %}
    <div class="list-group">
    {% for invoice in invoices %}
      <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">${{ invoice.invoice_amount }} {{ invoice.status|upper }}</h5>
          <small>{{ invoice.invoice_date }}</small>
        </div>
        <p class="mb-1">{{ invoice.description }}</p>
        <small>
            {% if invoice.status == 'paid' %}
                Paid ${{ invoice.paid_amount }} on {{ invoice.paid_date }}
            {% elif invoice.status == 'refunded' %}
                Refunded ${{ invoice.refund_amount }} on {{ invoice.refund_date }}
            {% endif %}

                {% if invoice.payment %}
                using <i>{{ invoice.payment.get_card }}</i>
                {% endif %}
        </small>
      </a>                    
    {% endfor %}
    </div>
{% else %}
    <p>You have no payments on file.</p>
{% endif %}

</div>
</div>
{% endblock %}