config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import reverse
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views

urlpatterns = [
    #url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^$', RedirectView.as_view(url='/billing/pay', permanent=False), name="home"),
    url(r'^about$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('rink.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^billing/', include('billing.urls', namespace='billing')),
    url(r'^legal/', include('legal.urls', namespace='legal')),
    url(r'^organization/', include('league.urls', namespace='league')),
    url(r'^register/', include('registration.urls', namespace="register")),
    url(r'^registration/', include('registration.urls_admin', namespace='registration')),
    url(r'^roster/', include('roster.urls', namespace='roster')),
    url(r'^tickets/', include('tickets.urls', namespace='tickets')),
    url(r'^voting/', include('voting.urls', namespace='voting')),

    url(r'^robots.txt',
        TemplateView.as_view(template_name='robots.txt', content_type='text/plain'),
        name="robots_file")




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

rink/league/urls.py
from django.urls import path

from . import views

app_name = 'league'
urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    
    path('<slug:organization_slug>/leagues/', views.LeagueAdminList.as_view(), name="league_list"),
    path('<slug:organization_slug>/league/', views.LeagueAdminCreate.as_view(), name="league_create"),
    path('<slug:organization_slug>/league/<slug:slug>', views.LeagueAdminUpdate.as_view(), name="league_update"),
    path('<slug:organization_slug>/permissions/', views.OrganizationPermissionsView.as_view(), name="organization_permissions"),
    path('<slug:organization_slug>/permission/', views.OrganizationPermissionsChange.as_view(), name="organization_permissions_create"),
    path('<slug:organization_slug>/permission/<int:user_id>', views.OrganizationPermissionsChange.as_view(), name="organization_permissions_update"),
    path('<slug:organization_slug>/create-user/', views.CreateUserView.as_view(), name="create_rink_user"),

    # League view switcher
    path('switch-leagues-view/<slug:league_slug>', views.SwitchLeagueView.as_view(), name="switch_league_view"),

    # Insurance Types Admin
    path('<slug:organization_slug>/league/<slug:slug>/insurance',
        views.LeagueInsuranceTypesListView.as_view(),
        name="insurance_list"),

    path('<slug:organization_slug>/league/<slug:slug>/insurance/<int:insurance_type_id>',
        views.LeagueInsuranceTypesChangeView.as_view(),
        name="insurance_change"),

    path('<slug:organization_slug>/league/<slug:slug>/insurance/new',
        views.LeagueInsuranceTypesCreateView.as_view(),
        name="insurance_create"),


    # Billing Groups Admin
    path('<slug:organization_slug>/league/<slug:slug>/billing-groups',
        views.LeagueBillingGroupsListView.as_view(),
        name="billing_groups_list"),

    path('<slug:organization_slug>/league/<slug:slug>/billing-groups/<int:billing_group_id>',
        views.LeagueBillingGroupsChangeView.as_view(),
        name="billing_groups_change"),

    path('<slug:organization_slug>/league/<slug:slug>/billing-groups/new',
        views.LeagueBillingGroupsCreateView.as_view(),
        name="billing_groups_create"),

    # User Tags
    path('<slug:organization_slug>/league/<slug:slug>/tags',
        views.LeagueTagsListView.as_view(),
        name="tags_list"),
]

rink/legal/urls.py
from django.urls import path

from . import views

app_name = 'legal'
urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    # Leage Admin Views
    path('admin/documents/', 
        views.LegalDocumentList.as_view(),
        name="admin_document_list"),

    path('admin/document/', 
        views.LegalDocumentCreateUpdate.as_view(),
        name="admin_document_create_update"),

    path('admin/document/<int:document_id>/', 
        views.LegalDocumentCreateUpdate.as_view(),
        name="admin_document_create_update"),

    path('admin/document/<int:document_id>/delete', 
        views.LegalDocumentDelete.as_view(),
        name="admin_document_delete"),


    # User Views
    path('signed-forms/', 
        views.UserLegalSignaturesListView.as_view(),
        name="signed_forms"),


    # Public Views
    path('<slug:league_slug>/<slug:document_slug>/',
        views.LegalDocumentPublicView.as_view(),
        name="view_legal_document"),

    path('<slug:league_slug>/event/<slug:event_slug>/',
        views.LegalDocumentEventView.as_view(),
        name="view_event_legal_documents"),
]

rink/users/urls.py
from django.urls import path

from . import views


app_name = 'users'
urlpatterns = [
    path('profile/', 
        views.UserProfileView.as_view(),
        name="profile"
    ),
]

rink/legal/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.utils.text import slugify

from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

import itertools


class LegalDocument(models.Model):
    league = models.ForeignKey(
        'league.League',
        on_delete=models.CASCADE,
        null=True,
    )

    name = models.CharField(
        "Document Name",
        max_length=100,
        help_text="Name of this legal document.",
    )

    slug = models.CharField(
        "Slug",
        max_length=100,
        blank=True,
    )

    date = models.DateField(
        "Effective Date",
        help_text="Effective date of this legal document.",
    )

    content = models.TextField(
        "Document Content",
        help_text="Plaintext version of the legal document. You can use <a target='_blank' href='https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet'>Markdown Code</a> to format the document.",
    )

    def __str__(self):
        return "{} ({})".format(self.name, self.date)

    @property
    def content_html(self):
        return markdownify(self.content)

    def get_absolute_url(self):
        return reverse('legal:view_legal_document', 
            kwargs={'league_slug': self.league.slug, 'document_slug': self.slug })

    class Meta:
        unique_together = ('slug', 'league')
        ordering = ['date', 'name']


class LegalSignature(models.Model):
    user = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        null=True
    )

    document = models.ForeignKey(
        'legal.LegalDocument',
        on_delete=models.CASCADE,
    )

    league = models.ForeignKey(
        'league.League',
        on_delete=models.CASCADE,
        null=True
    )

    event = models.ForeignKey(
        'registration.RegistrationEvent',
        on_delete=models.SET_NULL,
        null=True,
    )

    registration = models.ForeignKey(
        'registration.RegistrationData',
        on_delete=models.SET_NULL,
        null=True,
    )

    agreed_by = models.CharField(
        "Agreed To By",
        max_length=20,
        default="participant",
        help_text="Typically this is either 'participant' or 'guardian', signifying who agreed to the document.",
    )

    agree_initials = models.CharField(
        "Initials",
        max_length=3,
        blank=True,
        help_text="If registration form requires user to initial agreeing to the documents, record that here.",
    )

    agree_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} - {} - {}".format(self.user, self.document, self.league)

    class Meta:
        ordering = ['agree_date', 'document__name']


@receiver(pre_save, sender=LegalDocument)
def slugify_legal_document(sender, instance, *args, **kwargs):
    instance.slug = original_slug = slugify("{} {}".format(instance.name, instance.date))

    obj = None
    try:
        obj = sender.objects.get(pk=instance.pk)
    except sender.DoesNotExist:
        pass # new object
    else:
        has_signatures = LegalSignature.objects.filter(document=obj)
        if has_signatures and (not obj.content == instance.content or not obj.date == instance.date):
            raise ValidationError("You cannot change the content or date of this legal document, as {} have signed it. Create a new legal document.".format(has_signatures.count()))

    # Check for uniqueness in the slug and resolve issues here
    # I suppose we could create thousands of the same slug here and have some
    # of issues resolving it, possibly outside of the max length of the slug
    # field and such.
    for slug_counter in itertools.count(1):
        search = LegalDocument.objects.filter(
            league=instance.league,
            slug=instance.slug
        )
        if obj:
            search.exclude(pk=obj.pk)

        if not search.exists():
            break
        instance.slug = '%s-%d' % (original_slug, slug_counter)

        if slug_counter >= settings.SLUG_RESOLVE_DUPLICATES_LIMIT:
            raise ValidationError("It looks like you have created {} of the same documents with the same name and date. Please remove those or use a different name or date on this one.".format(settings.SLUG_RESOLVE_DUPLICATES_LIMIT))

rink/roster/models.py
from django.db import models

# Create your models here.

rink/billing/forms.py
from django import forms
from django.utils import timezone
from crispy_forms.helper import FormHelper

from .models import PAYMENT_PROCESSOR_CHOICES, Invoice


class UpdateStripeCardForm(forms.Form):
    stripe_token = forms.CharField(max_length=50)


class PayNowForm(forms.Form):
    invoice_id = forms.IntegerField()


class InvoiceFilterForm(forms.Form):
    # For Invoice Admin filtering form
    search = forms.CharField(max_length=200, label='', required=False)
    paid = forms.BooleanField(initial=True, required=False)
    unpaid = forms.BooleanField(initial=True, required=False)
    refunded = forms.BooleanField(initial=True, required=False)
    canceled = forms.BooleanField(initial=True, required=False)
    filtered = forms.BooleanField(initial=True, required=False, widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.fields['search'].widget.attrs.update({'placeholder': "Search #, Name, Email"})


class QuickPaymentForm(forms.Form):
    processor = forms.ChoiceField(choices=PAYMENT_PROCESSOR_CHOICES, required=True, initial='cash')
    amount = forms.DecimalField(min_value=0.00, decimal_places=2)
    transaction_id = forms.CharField(max_length=200, required=False)
    payment_date = forms.DateField(initial=timezone.now())


class QuickInvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = ['invoice_amount', 'description', 'status', 'invoice_date', 'due_date']


class QuickRefundForm(forms.Form):
    refund_amount = forms.DecimalField(min_value=0.00, decimal_places=2)
    refund_reason = forms.CharField(max_length=200, required=False)

rink/billing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views import View

from .forms import UpdateStripeCardForm, PayNowForm
from .models import UserStripeCard, Invoice, BillingPeriod
from league.models import League

from stripe.error import CardError


class PayView(LoginRequiredMixin, View):
    template_name = "billing/pay.html"

    def get(self, request):
        league = League.objects.get(pk=request.session['view_league'])
        try:
            user_stripe_card = UserStripeCard.objects.get(user=request.user, league=league)
        except UserStripeCard.DoesNotExist:
            user_stripe_card = None

        invoices = Invoice.objects.filter(
            user=request.user,
            league=league,
            status='unpaid',
        )

        future_invoices = BillingPeriod.objects.filter(
            event__league=league,
            event__billingsubscription__user=request.user,
            event__billingsubscription__status='active',
            invoice_date__gte=timezone.now(),
        )

        for invoice in future_invoices:
            invoice.invoice_amount = invoice.get_invoice_amount(user=request.user)

        return render(request, self.template_name, {
            'invoices': invoices,
            'future_invoices': future_invoices,
            'user_stripe_card': user_stripe_card,
            'current_time': timezone.now(),
        })

    def post(self, request):
        # I suppose we could show form errors here, but whatever
        league = League.objects.get(pk=request.session['view_league'])
        form = PayNowForm(data=request.POST)

        if form.is_valid():
            try:
                invoice = Invoice.objects.get(
                    pk=form.cleaned_data['invoice_id'],
                    user=request.user,
                    league=league,
                    status='unpaid',
                )
            except Invoice.DoesNotExist:
                return redirect('billing:pay')

            if invoice.invoice_amount == 0:
                invoice.pay()
                messages.success(request, "<strong>$0 Payment successful!</strong> Thanks.</p>")
                return redirect('billing:pay')

            try:
                user_stripe_card = UserStripeCard.objects.get(user=request.user, league=league)
            except UserStripeCard.DoesNotExist:
                messages.error(request, "You do not have a credit card saved. Please save a credit card before attempting to pay an invoice. Sorry. Thanks.")
                return redirect('billing:pay')

            try:
                user_stripe_card.charge(invoice=invoice)
                messages.success(request, "<strong>Payment successful!</strong> We emailed you a receipt. Thanks.</p>")
            except ValueError as e:
                messages.error(request, e)
                return redirect('billing:pay')
            except CardError as e:
                body = e.json_body
                err = body.get('error', {})
                messages.error(request, "<p>We were unable to charge your credit card.</p>\
                    <p>Reason: {}</p>\
                    <p>Please try again or contact us if you continue to have issues.</p>".format(
                    err.get('message')))

        return redirect('billing:pay')


class PaymentHistoryView(LoginRequiredMixin, View):
    template_name = "billing/payment_history.html"

    def get(self, request):
        invoices = Invoice.objects.filter(
            user=request.user,
            league=League.objects.get(pk=request.session['view_league']),
        ).exclude(status='unpaid')

        return render(request, self.template_name, {
            'invoices': invoices,
        })


class UpdateUserStripeCardView(LoginRequiredMixin, View):
    template_name = "billing/update_card.html"

    def get(self, request):
        try:
            user_stripe_card = UserStripeCard.objects.get(
                user=request.user,
                league=League.objects.get(pk=request.session['view_league']),
            )
        except UserStripeCard.DoesNotExist:
            user_stripe_card = None

        return render(request, self.template_name, {
            'user_stripe_card': user_stripe_card,
        })

    def post(self, request):
        form = UpdateStripeCardForm(data=request.POST)
        if form.is_valid():
            card_profile, created = UserStripeCard.objects.get_or_create(
                user=request.user,
                league=League.objects.get(pk=request.session['view_league']),
            )

        try:
            card_profile.update_from_token(form.cleaned_data['stripe_token'])
            #payment = card_profile.charge(invoice=invoice, send_receipt=False)
            messages.success(request, "Card on file has been updated. Thanks!")
        except CardError as e:
            body = e.json_body
            err = body.get('error', {})
            messages.error(request, "<p>We were unable to save your credit card.</p>\
                <p>Reason: {}</p>\
                <p>Please try again or contact us if you continue to have issues.</p>".format(
                err.get('message'))
            )
        return redirect('billing:update_card')

rink/templates/legal/admin_document_create_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ document.name }} - Edit Legal Document{% endblock %}

{% block content %}

<h2>{% if document %}Edit {{ document.name }} ({{ document.date }}){% else %}New Legal Document{% endif %}</h2>

{% include 'utils/messages.html' %}

{% if document.count > 0 %}
<div class="alert alert-warning" role="alert">
  You are no longer able to edit the date or content of this legal document. <strong>It has been agreed to by {{ document.count }} people.</strong> Please create a new document and assign it to a registration form.
</div>
{% endif %}

{% if document.id %}
<div class="alert alert-light" role="alert">
<strong>Public Link:</strong> This document can be <a href="{% url 'legal:view_legal_document' league_slug=document.league.slug document_slug=document.slug %}" target="_blank">publically viewed at this link.</a>
</div>
{% endif %}

{% crispy form %}


{% if document.count == 0 %}
<br/>
<br/>

<a href="{% url 'legal:admin_document_delete' document_id=document.pk %}">
<button type="button" class="btn btn-outline-danger">Delete Document</button>
</a>
{% endif %}

{% endblock %}

rink/templates/legal/admin_document_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Legal Documents{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3">

<div class="row mt-3 mb-3">
    <div class="col">
        <h3>Legal Documents</h3>
    </div>
    <div class="col text-right">
        <a href="{% url 'legal:admin_document_create_update' %}">
            <button type="button" class="btn btn-primary btn-sm">Create Legal Document</button>
        </a>
    </div>
</div>

{% include 'utils/messages.html' %}

<ul class="list-group">
{% for document in object_list %}
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="{% url 'legal:admin_document_create_update' document_id=document.pk %}">{{ document.name }} ({{ document.date }})</a>
    <span class="badge badge-primary badge-pill">{{ document.legalsignature__count }}</span>
  </li>
{% endfor %}
</ul>

</div>
</div>
{% endblock %}

rink/templates/legal/event_documents.html
{% extends 'base.html' %}

{% block title %}Legal Forms - {{ event.name }}{% endblock %}



{% block content %}
<h2 id="doclist">Legal Forms for {{ event.name }}</h2>

{% if event.legal_forms.count == 0 and event.legal_forms_guardian.count == 0 %}
    No forms are attached to this event. There may be forms required to be signed on paper.



{% else %}
<p>Participating in this event requires agreement to the following documents.</p>

{% if event.form_type == 'minor' %}

    {% if event.legal_forms_guardian.count > 0 %}
    <h5>Parent / Guardian Documents</h5>
    <div class="list-group" style="max-width:600px;">
            {% for document in event.legal_forms_guardian.all %}
            <a class="list-group-item" href="#doc{{ document.id }}-guardian">
                {{ document.name }} - {{ document.date }}
            </a>
            {% endfor %}
    </div>
    {% endif %}

    {% if event.legal_forms.count > 0 %}
    <h5 class="mt-3">Skater / Participant Documents</h5>
    <div class="list-group" style="max-width:600px;">
            {% for document in event.legal_forms.all %}
            <a class="list-group-item" href="#doc{{ document.id }}-participant">
                {{ document.name }} - {{ document.date }}
            </a>
            {% endfor %}
    </div>
    {% endif %}

    <div style="height:120px"></div>
    <hr class="mt-5 mb-5">

    {% if event.legal_forms_guardian.count > 0 %}
    
    <h5>Parent / Guardian - Documents</h5>

    {% for document in event.legal_forms_guardian.all %}
    <div class="container" style="margin-bottom:50px">
        <div class="row">
            <h4 id="doc{{ document.id }}-guardian">{{ document.name }} - {{ document.date }}</h4>
        </div>
        <div class="row">
            {{ document.content_html|safe }}
        </div>
        <div class="row">
            <a href="#doclist" class="text-muted" style="text-decoration:underline">Back to Document List</a>
        </div>
    </div>
    <hr class="mt-5 mb-5">
    {% endfor %}
    {% endif %}

    {% if event.legal_forms.count > 0 %}
    <h5>Skater / Participant - Documents</h5>

    {% for document in event.legal_forms.all %}
    <div class="container" style="margin-bottom:50px">
        <div class="row">
            <h4 id="doc{{ document.id }}-participant">{{ document.name }} - {{ document.date }}</h4>
        </div>
        <div class="row">
            {{ document.content_html|safe }}
        </div>
        <div class="row">
            <a href="#doclist" class="text-muted" style="text-decoration:underline">Back to Document List</a>
        </div>
    </div>
    <hr class="mt-5 mb-5">
    {% endfor %}
    {% endif %}

{% else %}
    <div class="list-group">
            {% for document in event.legal_forms.all %}
            <a class="list-group-item" href="#doc{{ document.id }}">
                {{ document.name }} - {{ document.date }}
            </a>
            {% endfor %}
    </div>

    <div style="height:30px"></div>

    {% for document in event.legal_forms.all %}
    <div class="container" style="margin-bottom:50px">
        <div class="row">
            <h4 id="doc{{ document.id }}">{{ document.name }} - {{ document.date }}</h4>
        </div>
        <div class="row">
            {{ document.content_html|safe }}
        </div>
        <div class="row">
            <a href="#doclist" class="text-muted" style="text-decoration:underline">Back to Document List</a>
        </div>
    </div>
    <hr class="mt-5 mb-5">
    {% endfor %}
{% endif %}


{% endif %}

{% endblock %}

rink/templates/legal/public_document.html
{% extends 'base.html' %}

{% block title %}{{ document.name }}{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <h1>{{ document.name }} ({{ document.date }})</h1>
    </div>
    <div class="row">
        {{ document.content_html|safe }}
    </div>
</div>

{% endblock %}

rink/templates/legal/user_signed_forms.html
{% extends 'base.html' %}

{% block title %}Signed Forms{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3">

<h2>Signed Forms</h2>

{% if registration_data %}
{% for reg in registration_data %}
<div class="card mb-4">
  <h5 class="card-header">{{ reg.event }}</h5>
    {% if reg.legalsignature_set.all.count > 0 %}
    <ul class="list-group list-group-flush">
    {% for signature in reg.legalsignature_set.all %}
        <li class="list-group-item">
            <a href="{% url 'legal:view_legal_document' document_slug=signature.document.slug league_slug=signature.document.league.slug %}" target="_blank" class="card-link">{{ signature.document.name }} ({{ signature.document.date }})</a>
            <p class="card-text">
                <small class="text-muted">
                    Agreed on {{ signature.agree_date }} by 
                    {% if reg.event.form_type == 'minor' %}
                        <i>'{{ signature.agreed_by }}'</i>.
                        {% if signature.agree_initials %}
                            Initialed by <strong>{{ signature.agree_initials }}</strong>.
                        {% endif %}
                    {% else %}
                        {{ reg.contact_first_name }} 
                        {{ reg.contact_last_name }}
                    {% endif %}
                </small>
            </p>
        </li>
    {% endfor %}
    </ul>
    {% else %}
    <small class="m-3">No forms signed online for this event. They might be on hard copy.</small>
    {% endif %}
</div>
{% endfor %}
{% else %}
<p>Apparently, we have no signed forms to show you here. They might be on hard copy.</p>
{% endif %}

</div>
</div>
{% endblock %}