config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import reverse
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views

urlpatterns = [
    #url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^$', RedirectView.as_view(url='/billing/pay', permanent=False), name="home"),
    url(r'^about$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('rink.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^billing/', include('billing.urls', namespace='billing')),
    url(r'^legal/', include('legal.urls', namespace='legal')),
    url(r'^organization/', include('league.urls', namespace='league')),
    url(r'^register/', include('registration.urls', namespace="register")),
    url(r'^registration/', include('registration.urls_admin', namespace='registration')),
    url(r'^roster/', include('roster.urls', namespace='roster')),
    url(r'^tickets/', include('tickets.urls', namespace='tickets')),
    url(r'^voting/', include('voting.urls', namespace='voting')),

    url(r'^robots.txt',
        TemplateView.as_view(template_name='robots.txt', content_type='text/plain'),
        name="robots_file")




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

rink/league/urls.py
from django.urls import path

from . import views

app_name = 'league'
urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    
    path('<slug:organization_slug>/leagues/', views.LeagueAdminList.as_view(), name="league_list"),
    path('<slug:organization_slug>/league/', views.LeagueAdminCreate.as_view(), name="league_create"),
    path('<slug:organization_slug>/league/<slug:slug>', views.LeagueAdminUpdate.as_view(), name="league_update"),
    path('<slug:organization_slug>/permissions/', views.OrganizationPermissionsView.as_view(), name="organization_permissions"),
    path('<slug:organization_slug>/permission/', views.OrganizationPermissionsChange.as_view(), name="organization_permissions_create"),
    path('<slug:organization_slug>/permission/<int:user_id>', views.OrganizationPermissionsChange.as_view(), name="organization_permissions_update"),
    path('<slug:organization_slug>/create-user/', views.CreateUserView.as_view(), name="create_rink_user"),

    # League view switcher
    path('switch-leagues-view/<slug:league_slug>', views.SwitchLeagueView.as_view(), name="switch_league_view"),

    # Insurance Types Admin
    path('<slug:organization_slug>/league/<slug:slug>/insurance',
        views.LeagueInsuranceTypesListView.as_view(),
        name="insurance_list"),

    path('<slug:organization_slug>/league/<slug:slug>/insurance/<int:insurance_type_id>',
        views.LeagueInsuranceTypesChangeView.as_view(),
        name="insurance_change"),

    path('<slug:organization_slug>/league/<slug:slug>/insurance/new',
        views.LeagueInsuranceTypesCreateView.as_view(),
        name="insurance_create"),


    # Billing Groups Admin
    path('<slug:organization_slug>/league/<slug:slug>/billing-groups',
        views.LeagueBillingGroupsListView.as_view(),
        name="billing_groups_list"),

    path('<slug:organization_slug>/league/<slug:slug>/billing-groups/<int:billing_group_id>',
        views.LeagueBillingGroupsChangeView.as_view(),
        name="billing_groups_change"),

    path('<slug:organization_slug>/league/<slug:slug>/billing-groups/new',
        views.LeagueBillingGroupsCreateView.as_view(),
        name="billing_groups_create"),

    # User Tags
    path('<slug:organization_slug>/league/<slug:slug>/tags',
        views.LeagueTagsListView.as_view(),
        name="tags_list"),
]

rink/legal/urls.py
from django.urls import path

from . import views

app_name = 'legal'
urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    # Leage Admin Views
    path('admin/documents/', 
        views.LegalDocumentList.as_view(),
        name="admin_document_list"),

    path('admin/document/', 
        views.LegalDocumentCreateUpdate.as_view(),
        name="admin_document_create_update"),

    path('admin/document/<int:document_id>/', 
        views.LegalDocumentCreateUpdate.as_view(),
        name="admin_document_create_update"),

    path('admin/document/<int:document_id>/delete', 
        views.LegalDocumentDelete.as_view(),
        name="admin_document_delete"),


    # User Views
    path('signed-forms/', 
        views.UserLegalSignaturesListView.as_view(),
        name="signed_forms"),


    # Public Views
    path('<slug:league_slug>/<slug:document_slug>/',
        views.LegalDocumentPublicView.as_view(),
        name="view_legal_document"),

    path('<slug:league_slug>/event/<slug:event_slug>/',
        views.LegalDocumentEventView.as_view(),
        name="view_event_legal_documents"),
]

rink/users/urls.py
from django.urls import path

from . import views


app_name = 'users'
urlpatterns = [
    path('profile/', 
        views.UserProfileView.as_view(),
        name="profile"
    ),
]

rink/billing/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.utils import timezone
from django.urls import reverse

from decimal import Decimal
import stripe
from stripe.error import CardError, InvalidRequestError

from taskapp.celery import app as celery_app


class BillingGroup(models.Model):
    name = models.CharField(
        "Status Name",
        max_length=50,
        help_text="Example: 'Injured', 'Member', 'Adminisration', 'Social'",
    )

    league = models.ForeignKey(
        "league.League",
        on_delete=models.CASCADE,
    )

    description = models.CharField(
        "Status Description",
        max_length=250,
        blank=True,
        help_text="Any details about what this status represents.",
    )

    invoice_amount = models.DecimalField(
        "Custom Dues Amount",
        max_digits=10,
        decimal_places=2,
        help_text="The amount we should bill a user matching this status for the billing period specified above.",
        validators=[MinValueValidator(Decimal('0.00'))],
    )

    default_group_for_league = models.BooleanField(
        "Is Default Billing Group",
        help_text="If selected, this is the default billing group that new users and events will assign people to.",
        default=False,
    )

    def __str__(self):
        default = ""
        if self.default_group_for_league:
            default = " (DEFAULT)"
        return "{} - {}{}".format(self.league.name, self.name, default)

    class Meta:
        unique_together = ('name', 'league')
        ordering = ['league', 'name']

    def get_absolute_url(self):
        return reverse('league:billing_groups_list', kwargs={
            'organization_slug': self.league.organization.slug,
            'slug': self.league.slug,
        })


class BillingPeriod(models.Model):
    name = models.CharField(
        "Billing Period Name",
        max_length=50,
        help_text="Example: 'July Dues''",
    )

    event = models.ForeignKey(
        "registration.RegistrationEvent",
        on_delete=models.CASCADE,
    )

    league = models.ForeignKey(
        "league.League",
        on_delete=models.CASCADE,
    )

    start_date = models.DateField(
        "Start Date",
        help_text="First day of this billing period."
    )

    end_date = models.DateField(
        "End Date",
        help_text="Last day of this billing period."
    )

    invoice_date = models.DateField(
        "Invoice Date",
        help_text="The date invoices will be sent out for this billing period."
    )

    due_date = models.DateField(
        "Due Date",
        help_text="The date payments are due. Automatic credit card billing will also occur on this day."
    )

    dues_amounts = models.ManyToManyField(
        'billing.BillingGroup',
        through='BillingPeriodCustomPaymentAmount',
    )

    class Meta:
        verbose_name = "Dues Billing Date"
        verbose_name_plural = "Dues Billing Dates"
        ordering = ['league', 'event', 'start_date']

    def __str__(self):
        return "{} - {} to {}".format(
            self.name,
            self.start_date,
            self.end_date,
        )

    def clean(self):
        if not self.start_date or not self.end_date:
            raise ValidationError("Start and End Dates are required, or they are invalid somehow (bad date, extra spaces).")

        if not self.invoice_date:
            raise ValidationError("Invoice date is required, or it invalid somehow (bad date, extra spaces).")

        if not self.due_date:
            raise ValidationError("Due date is required, or it is invalid somehow (bad date, extra spaces).")

        # Start date needs to come before End date
        if self.start_date > self.end_date:
            raise ValidationError("End date invalid, should be a date after Start Date. Did you switch start and end dates?")
        # Invoice date needs to come before due date
        if self.invoice_date > self.due_date:
            raise ValidationError("Invoice date needs occur before Due date. We cannot process payments before they are actually billed. Did you swap the invoice and due dates?")

    def get_invoice_amount(self, billing_group=None, user=None):
        if user and billing_group:
            raise ValueError("Do not pass both billing_group and user to get_invoice_amount")
      
        if user:
            try:
                membership = BillingGroupMembership.objects.get(
                    league=self.league,
                    user=user
                )
            except BillingGroupMembership.DoesNotExist:
                pass
            else:
                billing_group = membership.group

        if billing_group:
            try:
                billing_schedule_obj = BillingPeriodCustomPaymentAmount.objects.get(
                    group=billing_group,
                    period=self,
                )
            except BillingPeriodCustomPaymentAmount.DoesNotExist:
                pass
            else:
                return billing_schedule_obj.invoice_amount

        # If we're still here, use the default amount in the billing_group
        if billing_group:
            return billing_group.invoice_amount

        # If for some reason no group was sent, but we have a billing period
        # use the default group for the league.
        try:
            default_group_for_league = BillingGroup.objects.get(
                league=self.league,
                default_group_for_league=True,
            )
        except BillingGroup.DoesNotExist:
            pass
        else:
            billing_group = default_group_for_league

        if billing_group:
            try:
                billing_schedule_obj = BillingPeriodCustomPaymentAmount.objects.get(
                    group=billing_group,
                    period=self,
                )
            except BillingPeriodCustomPaymentAmount.DoesNotExist:
                pass
            else:
                return billing_schedule_obj.invoice_amount
        
        if billing_group:
            return billing_group.invoice_amount

        # If we are STILL here, that means NO valid billing group set and
        # the billing period/group through table doesn't have an entry.
        # I guess give them a free ride?
        return 0

    def get_invoice_description(self, description="Registration"):
        return "{} {}".format(self.event.name, description)

    def generate_invoice(self, subscription, description="Registration"):
        # returns (object, created_True_or_False)
        return Invoice.objects.get_or_create(
            league=self.league,
            billing_period=self,
            user=subscription.user,
            subscription=subscription,
            defaults={
                'invoice_amount': self.get_invoice_amount(user=subscription.user),
                'invoice_date': timezone.now(),
                'due_date': self.due_date,
                'description': self.get_invoice_description(description),
            }
        )


class BillingGroupMembership(models.Model):
    group = models.ForeignKey(
        'billing.BillingGroup',
        on_delete=models.CASCADE,
    )

    league = models.ForeignKey(
        'league.League',
        on_delete=models.CASCADE,
    )

    user = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return "{} - {} - {}".format(self.league.name, self.group.name, self.user)

    class Meta:
        unique_together = ['user', 'league']


class BillingPeriodCustomPaymentAmount(models.Model):
    group = models.ForeignKey(
        'billing.BillingGroup',
        on_delete=models.CASCADE,
    )

    invoice_amount = models.DecimalField(
        "Custom Dues Amount",
        max_digits=10,
        decimal_places=2,
        help_text="The amount we should bill a user matching this status for the billing period specified above.",
        default=Decimal('0.00'),
    )

    period = models.ForeignKey(
        'billing.BillingPeriod',
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = "Billing Period Amount for Group"
        verbose_name_plural = "Billing Period Amounts for Groups"
        ordering = ['group__name']
        unique_together = ['group', 'period']

    def __str__(self):
        return "{} - {} - ${}".format(self.group.name, self.period.name, self.invoice_amount)

    def clean(self):
        if self.invoice_amount == "":
            self.invoice_amount = Decimal('0.00')

        if self.invoice_amount < 0:
            raise ValidationError("Invoice amount must be a positive number.")


BILLING_SUBSCRIPTION_CHOICES = [
    ('active', 'Active'),
    ('inactive', 'Inactive'),
    ('completed', 'Completed'),
]


class BillingSubscription(models.Model):
    user = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
    )

    league = models.ForeignKey(
        'league.League',
        on_delete=models.CASCADE,
    )

    event = models.ForeignKey(
        "registration.RegistrationEvent",
        on_delete=models.CASCADE,
    )

    roster = models.ForeignKey(
        "registration.Roster",
        on_delete=models.SET_NULL,
        null=True,
    )

    status = models.CharField(
        "Billing Status",
        max_length=50,
        choices=BILLING_SUBSCRIPTION_CHOICES,
        default="active",
    )

    create_date = models.DateTimeField(
        "Active Date",
        help_text="The date this subscription was created.",
        auto_now_add=True,
    )

    deactive_date = models.DateTimeField(
        "Deactivate Date",
        help_text="The date this subscription was deactivated.",
        blank=True,
        null=True,
    )

    class Meta:

rink/roster/models.py
from django.db import models

# Create your models here.

rink/legal/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import LegalDocument


class LegalDocumentAdminForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        super(LegalDocumentAdminForm, self).__init__(*args, **kwargs)
        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = LegalDocument
        fields = [
            'name',
            'date',
            'content',
        ]
        widgets = {
            'date': forms.TextInput(attrs={'type':'date'}),
        }

rink/tickets/forms.py
from django import forms


class TicketForm(forms.Form):
    real_name = forms.CharField(max_length=100, required=True)
    derby_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)
    stripe_token = forms.CharField(max_length=50, required=True)

rink/users/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import User


class UserProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = User
        fields = [
            'email',
            'first_name',
            'last_name',
            'derby_name',
            'derby_number',
        ]

rink/templates/league/create_rink_user.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create Rink User{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <h1>Create Admin User</h1>
    </div>
    <div class="row">
        <p>Use this form to quickly add someone to the system as an admin. They will receive an email with a temporary password.</p>
    </div>
</div>

{% crispy form %}

{% endblock %}

rink/templates/league/league_billing_groups_list.html
<h4>Billing Groups</h4>

<div class="container mt-3">
    <div class="row">
        <a href="{% url 'league:billing_groups_create' organization_slug=organization_slug slug=league_slug %}">
            <button type="button" class="btn btn-primary btn-sm">Create Billing Group</button>
        </a>
    </div>
</div>

<div class="container mt-3">
    <div class="row">
        <div class="list-group">
        {% for bg in billinggroup_list %}
            <a href="{% url 'league:billing_groups_change' organization_slug=organization_slug slug=league_slug billing_group_id=bg.pk %}" class="list-group-item list-group-item-action">
                <strong>{{ bg.name }}</strong> - ${{ bg.invoice_amount}}
                {% if bg.default_group_for_league %}
                    <span class="badge badge-primary">DEFAULT</span>
                {% endif %}
            
                {% if bg.description %}
                <br><span class="text-muted">{{ bg.description }}</span>
                {% endif %}
            </a>
        {% endfor %}
        </div>
    </div>
</div>

rink/templates/league/league_billing_groups_update.html
{% load bootstrap4 %}

<h4>{% if billinggroup %}Update <strong>'{{ billinggroup.name }}'</strong>{% else %}Create{% endif %} Billing Group</h4>

<div class="container">
    <div class="row">
        <form method="post">{% csrf_token %}

          {% bootstrap_form form %}
          {% buttons %}
            <button type="submit" class="btn btn-primary">
              Submit
            </button>
            <a class="ml-5" href="{% url 'league:billing_groups_list' organization_slug=organization_slug slug=league_slug %}">
                <button type="button" class="btn btn-secondary">Go Back</button>
            </a>
          {% endbuttons %}

        </form>
    </div>
</div>

rink/templates/league/league_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Manage League{% endblock %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    {% if request.session.organization_admin %}<li class="breadcrumb-item"><a href="{% url 'league:league_list' organization_slug=request.user.organization.slug %}">Manage Leagues</a></li>{% endif %}
    <li class="breadcrumb-item active" aria-current="page">{% if league %}Edit{% else %}New{% endif %} League {% if not request.session.organization_admin %} Settings{% endif %}</li>
  </ol>
</nav>

<div class="container">
    <div class="row mb-3">
        {% if league.logo %}
            <img src="{{ league.logo_thumbnail_header.url }}" alt="{{ league.name }} logo" class="img-thumbnail">
        {% endif %}
        <h1 style="margin:5px 0 0 15px;">{% if league %}{{ league }}{% else %}New League{% endif %}</h1>
    </div>

    {% if warning %}
        <div class="alert alert-warning" role="alert">
            {{ warning|safe }}
        </div>
    {% endif %}

    {% include 'utils/messages.html' %}
    
    {% include 'league/league_menu.html' with base_settings_url=base_settings_url selected_tab=selected_tab organization_slug=league.organization.slug league_slug=league.slug %}

    <div class="row mt-3">
        {% if selected_tab == "insurance" %}
            {% if form %}
                {% include 'league/league_insurance_update.html' with insurancetype=insurancetype form=form organization_slug=league.organization.slug league_slug=league.slug %}
            {% else %}
                {% include 'league/league_insurance_list.html' with insurancetype_list=insurancetype_list organization_slug=league.organization.slug league_slug=league.slug %}
            {% endif %}
        {% elif selected_tab == "billing_group" %}
            {% if form %}
                {% include 'league/league_billing_groups_update.html' with billinggroup=billinggroup form=form organization_slug=league.organization.slug league_slug=league.slug %}
            {% else %}
                {% include 'league/league_billing_groups_list.html' with billinggroup_list=billinggroup_list organization_slug=league.organization.slug league_slug=league.slug %}
            {% endif %}
        {% elif selected_tab == "tags" %}
            {% include 'league/league_tags_list.html' with tags_list=tags_list organization_slug=league.organization.slug league_slug=league.slug %}
        {% else %}
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-name" role="tabpanel" aria-labelledby="nav-name-tab">
            {% crispy forms.name_form %}
            </div>
            <div class="tab-pane fade" id="nav-billing" role="tabpanel" aria-labelledby="nav-billing-tab">
            {% crispy forms.billing_form %}
            </div>
            <div class="tab-pane fade" id="nav-registration" role="tabpanel" aria-labelledby="nav-registration-tab">
            {% crispy forms.registration_form %}
            </div>
            <div class="tab-pane fade" id="nav-branding" role="tabpanel" aria-labelledby="nav-branding-tab">
            {% crispy forms.branding_form %}
            </div>
            <div class="tab-pane fade" id="nav-email" role="tabpanel" aria-labelledby="nav-email-tab">
            {% crispy forms.email_form %}
            </div>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

rink/templates/league/league_insurance_list.html
<h4>Insurance Types</h4>

<div class="container mt-3">
    <div class="row">
        <a href="{% url 'league:insurance_create' organization_slug=organization_slug slug=league_slug %}">
            <button type="button" class="btn btn-primary btn-sm">Create Insurance Type</button>
        </a>
    </div>
</div>

<div class="container mt-3">
    <div class="row">
        <div class="list-group">
        {% for ins in insurancetype_list %}
            <a href="{% url 'league:insurance_change' organization_slug=organization_slug slug=league_slug insurance_type_id=ins.pk %}" class="list-group-item list-group-item-action">
                <strong>{{ ins.name }}</strong>
            
                {% if ins.long_name %}
                <br><span class="text-muted">{{ ins.long_name }}</span>
                {% endif %}
            </a>
        {% endfor %}
        </div>
    </div>
</div>

rink/templates/league/league_insurance_update.html
{% load bootstrap4 %}

<h4>{% if insurancetype %}Update <strong>'{{ insurancetype.name }}'</strong>{% else %}Create{% endif %} Insurance Type</h4>

<div class="container">
    <div class="row">
        <form method="post">{% csrf_token %}

          {% bootstrap_form form %}
          {% buttons %}
            <button type="submit" class="btn btn-primary">
              Submit
            </button>
            <a class="ml-5" href="{% url 'league:insurance_list' organization_slug=organization_slug slug=league_slug %}">
                <button type="button" class="btn btn-secondary">Go Back</button>
            </a>
          {% endbuttons %}

        </form>
    </div>
</div>

rink/templates/league/league_list.html
{% extends 'base.html' %}

{% block title %}Manage Leagues{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <h3>Manage Leagues</h3>
    </div>
    <div class="row mt-3 mb-3">
        <a href="{% url 'league:league_create' organization_slug=request.user.organization.slug %}">
            <button type="button" class="btn btn-primary btn-sm">Create League</button>
        </a>
    </div>
    <div class="row">
        {% if leagues %}
            <div class="list-group">
                {% for league in leagues %}
                    <a href="{% url 'league:league_update' slug=league.slug organization_slug=request.user.organization.slug %}" class="list-group-item list-group-item-action">
                        {% if league.logo_thumbnail %}
                            <img src="{{ league.logo_thumbnail.url }}" alt="{{ league.name }} logo" class="img-thumbnail">
                        {% endif %}
                        {{ league.name }}
                    </a>
                {% endfor %}
            </div>
        {% else %}
            No Leagues found. Maybe you should create one?
        {% endif %}
    </div>

</div>

{% endblock %}

rink/templates/league/league_menu.html
   <div class="row mt-3">
        <nav>
          <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link {% if not selected_tab %}active{% endif %}" id="nav-name-tab" {% if not base_settings_url %}data-toggle="tab"{% endif %} href="{{ base_settings_url }}#nav-name" role="tab" aria-controls="nav-home" aria-selected="true">Name and Image</a>
            <a class="nav-item nav-link" id="nav-billing-tab" {% if not base_settings_url %}data-toggle="tab"{% endif %} href="{{ base_settings_url }}#nav-billing" role="tab" aria-controls="nav-profile" aria-selected="false">Billing</a>
            <a class="nav-item nav-link" id="nav-registration-tab" {% if not base_settings_url %}data-toggle="tab"{% endif %} href="{{ base_settings_url }}#nav-registration" role="tab" aria-controls="nav-contact" aria-selected="false">Registration</a>
            <a class="nav-item nav-link" id="nav-email-tab" {% if not base_settings_url %}data-toggle="tab"{% endif %}href="{{ base_settings_url }}#nav-email" role="tab" aria-controls="nav-contact" aria-selected="false">Email</a>
            <a class="nav-item nav-link" id="nav-branding-tab" {% if not base_settings_url %}data-toggle="tab"{% endif %}href="{{ base_settings_url }}#nav-branding" role="tab" aria-controls="nav-contact" aria-selected="false">Branding</a>
            <a class="nav-item nav-link {% if selected_tab == "billing_groups"%} active{% endif %}" id="nav-groups-tab" href="{% url 'league:billing_groups_list' organization_slug=organization_slug slug=league_slug %}" role="tab">Billing Groups</a>
            <a class="nav-item nav-link {% if selected_tab == "insurance"%} active{% endif %}" id="nav-insurance-tab" href="{% url 'league:insurance_list' organization_slug=organization_slug slug=league_slug %}" role="tab" >Insurance</a>
            <a class="nav-item nav-link {% if selected_tab == "tags"%} active{% endif %}" id="nav-tags-tab" href="{% url 'league:tags_list' organization_slug=organization_slug slug=league_slug %}" role="tab" >User Tags</a>
          </div>
        </nav>
    </div>

rink/templates/league/league_tags_list.html
<h4>User Tags</h4>

<div class="container mt-3">
    <div class="row">
    </div>
</div>

<div class="container mt-3">
    <div class="row">
        <div class="list-group">
        {% for tag in object_list %}
            {{ tag.text }}<br>
        {% endfor %}
        </div>
    </div>
</div>

rink/templates/league/permissions_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ user }} - Permissions{% endblock %}

{% block content %}

<h2>{{ user }} - Permissions</h2>

{% crispy form %}

{% endblock %}

rink/templates/league/permissions_list.html
{% extends 'base.html' %}

{% block title %}Organization Permissions{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <h3>Organization Admins</h3>
    </div>
</div>

{% if organization.users %}
<div class="list-group">
    {% for user in organization.users %}
        <a href="{% url 'league:organization_permissions_update' user_id=user.pk organization_slug=organization.slug %}">
            <button type="button" class="list-group-item list-group-item-action">
                {{ user }}
                <span class="badge badge-pill badge-danger">org admin</span>
            </button>
        </a>
    {% endfor %}
</div>
{% else %}
No organization admins have been set. Which is weird. How are you here?
{% endif %}



{% for league in leagues %}
<div class="container mt-5">
    <div class="row">
        <h3>
            <img src="{{ league.logo_thumbnail.url }}" alt="{{ league.name }} logo" class="img-thumbnail">
                        {{ league.name }}
        </h3>
    </div>
</div>

{% if league.users %}
    <div class="list-group">
        {% for user, permissions in league.users.items %}
            <a href="{% url 'league:organization_permissions_update' user_id=user.pk organization_slug=organization.slug %}" class="list-group-item list-group-item-action">

                {{ user }}

                {% for permission in permissions %}
                    {% if permission not in ignore %}
                        <span class="badge badge-pill badge-primary">{{ permission }}</span>
                    {% endif %}
                {% endfor %}
            </a>
        {% endfor %}
    </div>
{% else %}
    No users in this league have admin privileges.
{% endif %}


{% endfor %}





{% endblock %}