config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import reverse
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views

urlpatterns = [
    #url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^$', RedirectView.as_view(url='/billing/pay', permanent=False), name="home"),
    url(r'^about$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('rink.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^billing/', include('billing.urls', namespace='billing')),
    url(r'^legal/', include('legal.urls', namespace='legal')),
    url(r'^organization/', include('league.urls', namespace='league')),
    url(r'^register/', include('registration.urls', namespace="register")),
    url(r'^registration/', include('registration.urls_admin', namespace='registration')),
    url(r'^roster/', include('roster.urls', namespace='roster')),
    url(r'^tickets/', include('tickets.urls', namespace='tickets')),
    url(r'^voting/', include('voting.urls', namespace='voting')),

    url(r'^robots.txt',
        TemplateView.as_view(template_name='robots.txt', content_type='text/plain'),
        name="robots_file")




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

rink/billing/urls.py
from django.urls import path

from . import views
from . import views_admin

app_name = 'billing'
urlpatterns = [
    path('admin', views_admin.BillingAdminView.as_view(), name="billing_admin"),
    path('admin/<int:pk>', views_admin.BillingAdminDetailView.as_view(), name="billing_admin_detail"),
    path('admin/<int:pk>/payment',
        views_admin.BillingAdminAddPaymentView.as_view(), name="billing_admin_add_payment"),
    path('admin/<int:pk>/refund', 
        views_admin.BillingAdminRefundPaymentView.as_view(), name="billing_admin_refund_payment"),
    path('admin/<int:pk>/edit', 
        views_admin.BillingAdminEditInvoiceView.as_view(), name="billing_admin_edit_invoice"),

    path('pay', views.PayView.as_view(), name="pay"),
    path('payments', views.PaymentHistoryView.as_view(), name="payment_history"),
    path('update-card', views.UpdateUserStripeCardView.as_view(), name="update_card"),

]

rink/league/urls.py
from django.urls import path

from . import views

app_name = 'league'
urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    
    path('<slug:organization_slug>/leagues/', views.LeagueAdminList.as_view(), name="league_list"),
    path('<slug:organization_slug>/league/', views.LeagueAdminCreate.as_view(), name="league_create"),
    path('<slug:organization_slug>/league/<slug:slug>', views.LeagueAdminUpdate.as_view(), name="league_update"),
    path('<slug:organization_slug>/permissions/', views.OrganizationPermissionsView.as_view(), name="organization_permissions"),
    path('<slug:organization_slug>/permission/', views.OrganizationPermissionsChange.as_view(), name="organization_permissions_create"),
    path('<slug:organization_slug>/permission/<int:user_id>', views.OrganizationPermissionsChange.as_view(), name="organization_permissions_update"),
    path('<slug:organization_slug>/create-user/', views.CreateUserView.as_view(), name="create_rink_user"),

    # League view switcher
    path('switch-leagues-view/<slug:league_slug>', views.SwitchLeagueView.as_view(), name="switch_league_view"),

    # Insurance Types Admin
    path('<slug:organization_slug>/league/<slug:slug>/insurance',
        views.LeagueInsuranceTypesListView.as_view(),
        name="insurance_list"),

    path('<slug:organization_slug>/league/<slug:slug>/insurance/<int:insurance_type_id>',
        views.LeagueInsuranceTypesChangeView.as_view(),
        name="insurance_change"),

    path('<slug:organization_slug>/league/<slug:slug>/insurance/new',
        views.LeagueInsuranceTypesCreateView.as_view(),
        name="insurance_create"),


    # Billing Groups Admin
    path('<slug:organization_slug>/league/<slug:slug>/billing-groups',
        views.LeagueBillingGroupsListView.as_view(),
        name="billing_groups_list"),

    path('<slug:organization_slug>/league/<slug:slug>/billing-groups/<int:billing_group_id>',
        views.LeagueBillingGroupsChangeView.as_view(),
        name="billing_groups_change"),

    path('<slug:organization_slug>/league/<slug:slug>/billing-groups/new',
        views.LeagueBillingGroupsCreateView.as_view(),
        name="billing_groups_create"),

    # User Tags
    path('<slug:organization_slug>/league/<slug:slug>/tags',
        views.LeagueTagsListView.as_view(),
        name="tags_list"),
]

rink/legal/urls.py
from django.urls import path

from . import views

app_name = 'legal'
urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    # Leage Admin Views
    path('admin/documents/', 
        views.LegalDocumentList.as_view(),
        name="admin_document_list"),

    path('admin/document/', 
        views.LegalDocumentCreateUpdate.as_view(),
        name="admin_document_create_update"),

    path('admin/document/<int:document_id>/', 
        views.LegalDocumentCreateUpdate.as_view(),
        name="admin_document_create_update"),

    path('admin/document/<int:document_id>/delete', 
        views.LegalDocumentDelete.as_view(),
        name="admin_document_delete"),


    # User Views
    path('signed-forms/', 
        views.UserLegalSignaturesListView.as_view(),
        name="signed_forms"),


    # Public Views
    path('<slug:league_slug>/<slug:document_slug>/',
        views.LegalDocumentPublicView.as_view(),
        name="view_legal_document"),

    path('<slug:league_slug>/event/<slug:event_slug>/',
        views.LegalDocumentEventView.as_view(),
        name="view_event_legal_documents"),
]

rink/users/urls.py
from django.urls import path

from . import views


app_name = 'users'
urlpatterns = [
    path('profile/', 
        views.UserProfileView.as_view(),
        name="profile"
    ),
]

rink/billing/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.utils import timezone
from django.urls import reverse

from decimal import Decimal
import stripe
from stripe.error import CardError, InvalidRequestError

from taskapp.celery import app as celery_app


class BillingGroup(models.Model):
    name = models.CharField(
        "Status Name",
        max_length=50,
        help_text="Example: 'Injured', 'Member', 'Adminisration', 'Social'",
    )

    league = models.ForeignKey(
        "league.League",
        on_delete=models.CASCADE,
    )

    description = models.CharField(
        "Status Description",
        max_length=250,
        blank=True,
        help_text="Any details about what this status represents.",
    )

    invoice_amount = models.DecimalField(
        "Custom Dues Amount",
        max_digits=10,
        decimal_places=2,
        help_text="The amount we should bill a user matching this status for the billing period specified above.",
        validators=[MinValueValidator(Decimal('0.00'))],
    )

    default_group_for_league = models.BooleanField(
        "Is Default Billing Group",
        help_text="If selected, this is the default billing group that new users and events will assign people to.",
        default=False,
    )

    def __str__(self):
        default = ""
        if self.default_group_for_league:
            default = " (DEFAULT)"
        return "{} - {}{}".format(self.league.name, self.name, default)

    class Meta:
        unique_together = ('name', 'league')
        ordering = ['league', 'name']

    def get_absolute_url(self):
        return reverse('league:billing_groups_list', kwargs={
            'organization_slug': self.league.organization.slug,
            'slug': self.league.slug,
        })


class BillingPeriod(models.Model):
    name = models.CharField(
        "Billing Period Name",
        max_length=50,
        help_text="Example: 'July Dues''",
    )

    event = models.ForeignKey(
        "registration.RegistrationEvent",
        on_delete=models.CASCADE,
    )

    league = models.ForeignKey(
        "league.League",
        on_delete=models.CASCADE,
    )

    start_date = models.DateField(
        "Start Date",
        help_text="First day of this billing period."
    )

    end_date = models.DateField(
        "End Date",
        help_text="Last day of this billing period."
    )

    invoice_date = models.DateField(
        "Invoice Date",
        help_text="The date invoices will be sent out for this billing period."
    )

    due_date = models.DateField(
        "Due Date",
        help_text="The date payments are due. Automatic credit card billing will also occur on this day."
    )

    dues_amounts = models.ManyToManyField(
        'billing.BillingGroup',
        through='BillingPeriodCustomPaymentAmount',
    )

    class Meta:
        verbose_name = "Dues Billing Date"
        verbose_name_plural = "Dues Billing Dates"
        ordering = ['league', 'event', 'start_date']

    def __str__(self):
        return "{} - {} to {}".format(
            self.name,
            self.start_date,
            self.end_date,
        )

    def clean(self):
        if not self.start_date or not self.end_date:
            raise ValidationError("Start and End Dates are required, or they are invalid somehow (bad date, extra spaces).")

        if not self.invoice_date:
            raise ValidationError("Invoice date is required, or it invalid somehow (bad date, extra spaces).")

        if not self.due_date:
            raise ValidationError("Due date is required, or it is invalid somehow (bad date, extra spaces).")

        # Start date needs to come before End date
        if self.start_date > self.end_date:
            raise ValidationError("End date invalid, should be a date after Start Date. Did you switch start and end dates?")
        # Invoice date needs to come before due date
        if self.invoice_date > self.due_date:
            raise ValidationError("Invoice date needs occur before Due date. We cannot process payments before they are actually billed. Did you swap the invoice and due dates?")

    def get_invoice_amount(self, billing_group=None, user=None):
        if user and billing_group:
            raise ValueError("Do not pass both billing_group and user to get_invoice_amount")
      
        if user:
            try:
                membership = BillingGroupMembership.objects.get(
                    league=self.league,
                    user=user
                )
            except BillingGroupMembership.DoesNotExist:
                pass
            else:
                billing_group = membership.group

        if billing_group:
            try:
                billing_schedule_obj = BillingPeriodCustomPaymentAmount.objects.get(
                    group=billing_group,
                    period=self,
                )
            except BillingPeriodCustomPaymentAmount.DoesNotExist:
                pass
            else:
                return billing_schedule_obj.invoice_amount

        # If we're still here, use the default amount in the billing_group
        if billing_group:
            return billing_group.invoice_amount

        # If for some reason no group was sent, but we have a billing period
        # use the default group for the league.
        try:
            default_group_for_league = BillingGroup.objects.get(
                league=self.league,
                default_group_for_league=True,
            )
        except BillingGroup.DoesNotExist:
            pass
        else:
            billing_group = default_group_for_league

        if billing_group:
            try:
                billing_schedule_obj = BillingPeriodCustomPaymentAmount.objects.get(
                    group=billing_group,
                    period=self,
                )
            except BillingPeriodCustomPaymentAmount.DoesNotExist:
                pass
            else:
                return billing_schedule_obj.invoice_amount
        
        if billing_group:
            return billing_group.invoice_amount

        # If we are STILL here, that means NO valid billing group set and
        # the billing period/group through table doesn't have an entry.
        # I guess give them a free ride?
        return 0

    def get_invoice_description(self, description="Registration"):
        return "{} {}".format(self.event.name, description)

    def generate_invoice(self, subscription, description="Registration"):
        # returns (object, created_True_or_False)
        return Invoice.objects.get_or_create(
            league=self.league,
            billing_period=self,
            user=subscription.user,
            subscription=subscription,
            defaults={
                'invoice_amount': self.get_invoice_amount(user=subscription.user),
                'invoice_date': timezone.now(),
                'due_date': self.due_date,
                'description': self.get_invoice_description(description),
            }
        )


class BillingGroupMembership(models.Model):
    group = models.ForeignKey(
        'billing.BillingGroup',
        on_delete=models.CASCADE,
    )

    league = models.ForeignKey(
        'league.League',
        on_delete=models.CASCADE,
    )

    user = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return "{} - {} - {}".format(self.league.name, self.group.name, self.user)

    class Meta:
        unique_together = ['user', 'league']


class BillingPeriodCustomPaymentAmount(models.Model):
    group = models.ForeignKey(
        'billing.BillingGroup',
        on_delete=models.CASCADE,
    )

    invoice_amount = models.DecimalField(
        "Custom Dues Amount",
        max_digits=10,
        decimal_places=2,
        help_text="The amount we should bill a user matching this status for the billing period specified above.",
        default=Decimal('0.00'),
    )

    period = models.ForeignKey(
        'billing.BillingPeriod',
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = "Billing Period Amount for Group"
        verbose_name_plural = "Billing Period Amounts for Groups"
        ordering = ['group__name']
        unique_together = ['group', 'period']

    def __str__(self):
        return "{} - {} - ${}".format(self.group.name, self.period.name, self.invoice_amount)

    def clean(self):
        if self.invoice_amount == "":
            self.invoice_amount = Decimal('0.00')

        if self.invoice_amount < 0:
            raise ValidationError("Invoice amount must be a positive number.")


BILLING_SUBSCRIPTION_CHOICES = [
    ('active', 'Active'),
    ('inactive', 'Inactive'),
    ('completed', 'Completed'),
]


class BillingSubscription(models.Model):
    user = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
    )

    league = models.ForeignKey(
        'league.League',
        on_delete=models.CASCADE,
    )

    event = models.ForeignKey(
        "registration.RegistrationEvent",
        on_delete=models.CASCADE,
    )

    roster = models.ForeignKey(
        "registration.Roster",
        on_delete=models.SET_NULL,
        null=True,
    )

    status = models.CharField(
        "Billing Status",
        max_length=50,
        choices=BILLING_SUBSCRIPTION_CHOICES,
        default="active",
    )

    create_date = models.DateTimeField(
        "Active Date",
        help_text="The date this subscription was created.",
        auto_now_add=True,
    )

    deactive_date = models.DateTimeField(
        "Deactivate Date",
        help_text="The date this subscription was deactivated.",
        blank=True,
        null=True,
    )

    class Meta:

rink/roster/models.py
from django.db import models

# Create your models here.

rink/legal/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import LegalDocument


class LegalDocumentAdminForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        super(LegalDocumentAdminForm, self).__init__(*args, **kwargs)
        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = LegalDocument
        fields = [
            'name',
            'date',
            'content',
        ]
        widgets = {
            'date': forms.TextInput(attrs={'type':'date'}),
        }

rink/templates/roster/admin_billing.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}


{% block title %}Billing - {{ user }}{% endblock %}


{% block content %}
{% include 'roster/submenu.html' with submenu_selected="billing" %}

{% crispy billing_group_form %}

<hr>

{% if invoices %}
<div class="container">
    <div class="row">
        <div class="col-3">
          <button type="button" class="float-right btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#createInvoiceModal">Create Invoice</button>
            <h5>Invoices</h5>
            

            <div class="mt-4 nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                {% for invoice in invoices %}
                <a class="nav-link {% if object.pk == invoice.pk %}active{% endif %}" id="v-pills-invoice{{ invoice.pk }}-tab" href="{% url 'roster:admin_billing_invoice' pk=user.pk invoice_id=invoice.pk %}" role="tab" {% if object.pk == invoice.pk %}aria-selected="true"{% endif %}>
                    {% if not invoice.description %}(No Description){% else %}{{ invoice.description }}{% endif %} <br>
                    ${{ invoice.invoice_amount }} <button type="button" class="btn disabled btn-sm btn-{% if object.pk != invoice.pk %}outline-{% endif%}{{ invoice.status_class }} text-uppercase">{{ invoice.status }}</button>
                    <br>
                    <small><i>{{ invoice.invoice_date }}</i></small>
                </a>
                {% endfor %}
        </div>
        </div>
        <div class="col-9">
            <div class="tab-content" id="v-pills-tabContent">
                <div class="col-sm">
                    <fieldset>
                        <legend>Invoice Details</legend>
                        <p><strong>Description:</strong> {% if not object.description %}(No Description){% else %}{{ object.description }}{% endif %} <br></p>
                        
                        <strong>Status:</strong> <button type="button" class="btn disabled btn-sm btn-outline-{{ object.status_class }} text-uppercase">{{ object.status }}</button><br>
                        <strong>Amount:</strong> ${{ object.invoice_amount }}<br>
                        <br>
                        <strong>Invoice Date:</strong> {{ object.invoice_date|date:"n/j/Y" }}<br>
                        <strong>Due Date:</strong> {{ object.due_date|date:"n/j/Y" }}<br>
                        <strong>Paid Date:</strong> {{ object.paid_date|date:"n/j/Y" }}<br>
                        <br>

                        {% if not object.payment %}
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addPaymentModal">Add Payment</button>
                        {% endif %}
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editInvoiceModal">Edit Invoice</button>
                    </fieldset>
                </div>
                {% if object.payment %}
                <div class="col-sm">
                    <fieldset>
                        <legend>Payment Details</legend>
                    
                        <strong>Amount:</strong> ${{ object.payment.amount }}<br><br>
                        <strong>Card:</strong> {{ object.payment.get_card }}<br>
                        <strong>Paid by:</strong> {{ object.payment.processor }} {{ object.payment.transaction_id }}<br>
                        <strong>Date:</strong> {{ object.payment.payment_date|date:"n/j/Y" }}<br>
                        <br>

                        {% if object.payment.is_refunded %}
                        <strong>Refund Amount:</strong> ${{ object.payment.refund_amount }}<br>
                        <strong>Refund Date:</strong> {{ object.payment.refund_date|date:"n/j/Y" }}<br>
                        <strong>Refund Reason:</strong> {{ object.payment.refund_reason }}<br>
                        <br>
                        {% endif %}
                        
                        {% if not object.payment.is_refunded %}
                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#sendRefundModal">Refund</button>
                        {% endif %}
                    </fieldset>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% else %}
<p>This user has no invoices.</p>
{% endif %}


{% if not object.payment and object.user %}
<div class="modal fade" id="addPaymentModal" tabindex="-1" role="dialog" aria-labelledby="addPaymentLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form id="addPaymentForm" action="{% url 'billing:billing_admin_add_payment' pk=object.pk %}?roster_view={{ user.pk }}" method="post" class="form">
      <div class="modal-header">
        <h5 class="modal-title" id="addPaymentLabel">Add Payment - Invoice #{{ object.pk }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% csrf_token %}
        {% crispy payment_form %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input class="btn btn-success" type="submit" value="Add Payment" onclick="$(this).prop('disabled', 'disabled').val('Saving...');$('#addPaymentForm').submit();">
      </div>
      </form>
    </div>
  </div>
</div>
{% endif %}


{% if object.user %}
<div class="modal fade" id="editInvoiceModal" tabindex="-1" role="dialog" aria-labelledby="editInvoiceLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form id="editInvoiceForm" action="{% url 'billing:billing_admin_edit_invoice' pk=object.pk %}?roster_view={{ user.pk }}" method="post" class="form">
      <div class="modal-header">
        <h5 class="modal-title" id="editInvoiceLabel">Edit Invoice - Invoice #{{ object.pk }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% csrf_token %}
        {% crispy invoice_form %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input class="btn btn-primary" type="submit" value="Edit Invoice" onclick="$(this).prop('disabled', 'disabled').val('Saving...');$('#editInvoiceForm').submit();">
      </div>
      </form>
    </div>
  </div>
</div>
{% endif %}

{% if object.payment and not object.payment.is_refunded %}
<div class="modal fade" id="sendRefundModal" tabindex="-1" role="dialog" aria-labelledby="sendRefundLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form id="sendRefundForm"  action="{% url 'billing:billing_admin_refund_payment' pk=object.pk %}?roster_view={{ user.pk }}" method="post" class="form">
      <div class="modal-header">
        <h5 class="modal-title" id="sendRefundLabel">Refund Payment - Invoice #{{ object.pk }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% csrf_token %}
        {% crispy refund_form %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input class="btn btn-warning" type="submit" value="Refund Payment" onclick="$(this).prop('disabled', 'disabled').val('Saving...');$('#sendRefundForm').submit();">
      </div>
      </form>
    </div>
  </div>
</div>
{% endif %}




<div class="modal fade" id="createInvoiceModal" tabindex="-1" role="dialog" aria-labelledby="createInvoiceLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form id="createInvoiceForm"  action="{% url 'roster:admin_billing_create' pk=user.pk %}" method="post" class="form">
      <div class="modal-header">
        <h5 class="modal-title" id="createInvoiceLabel">Create Invoice for {{ user }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% csrf_token %}
        {% crispy create_invoice_form %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input class="btn btn-warning" type="submit" value="Create Invoice" onclick="$(this).prop('disabled', 'disabled').val('Saving...');$('#createInvoiceForm').submit();">
      </div>
      </form>
    </div>
  </div>
</div>




{% endblock %}

rink/templates/roster/admin_legal.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}


{% block title %}Signed Forms - {{ user }}{% endblock %}


{% block content %}
{% include 'roster/submenu.html' with submenu_selected="legal" %}


<div class="row">
  <div class="col-md-6 offset-md-3">

{% if registration_data %}
<p>Forms signed during event registration by <strong>{{ user }}</strong>:</p>
{% for reg in registration_data %}
<div class="card">
  <h5 class="card-header">{{ reg.event }}</h5>
    <ul class="list-group list-group-flush">
    {% for signature in reg.legalsignature_set.all %}
        <li class="list-group-item">
            <a href="{% url 'legal:view_legal_document' document_slug=signature.document.slug league_slug=signature.document.league.slug %}" target="_blank" class="card-link">{{ signature.document.name }} ({{ signature.document.date }})</a>
            <p class="card-text">
                <small class="text-muted">
                    Agreed on {{ signature.agree_date }} by 
                    {% if reg.event.form_type == 'minor' %}
                        <i>'{{ signature.agreed_by }}'</i>
                        . Initialed by <strong>{{ signature.agree_initials }}</strong>.
                    {% else %}
                        {{ reg.contact_first_name }} 
                        {{ reg.contact_last_name }}
                    {% endif %}
                </small>
            </p>
        </li>
    {% endfor %}
    </ul>
</div>
{% endfor %}
{% else %}
<p>Apparently, we have no signed forms for {{ user }} to show you here. They might be on hard copy.</p>
{% endif %}

</div>
</div>


{% endblock %}

rink/templates/roster/admin_notes.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}User Notes - {{ user }}{% endblock %}


{% block content %}
{% include 'roster/submenu.html' with submenu_selected="notes" %}


<div class="row">
  <div class="col-md-6 offset-md-3">

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addNoteModal">Add Note</button>

<hr>

{% if userlog_list %}
    {% for userlog in userlog_list %}


    <div class="card" style="margin-bottom:10px">
        <div class="card-header bg-{{ userlog.message_type }}">{{ userlog.group|title }}</div>
        <div class="card-body">
            {{ userlog.message_html|safe }}
            {% if userlog.content_object.get_admin_url %}<a href="{{ userlog.content_object.get_admin_url }}" class="card-link">View Details</a>{% endif %}
            <br>
            <small class="text-muted">{{ userlog.date }}{% if userlog.admin_user %} by {{ userlog.admin_user }}{% endif %}</small>
        </div>
    </div>

    {% endfor %}
{% else %}
<p>We have no notes or logs for {{ user }} to show you here.</p>
{% endif %}


</div>
</div>



<div class="modal fade" id="addNoteModal" tabindex="-1" role="dialog" aria-labelledby="addNoteLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form id="addNoteForm"  action="{% url 'roster:admin_notes_add' pk=user.pk %}" method="post" class="form">
      <div class="modal-header">
        <h5 class="modal-title" id="addNoteLabel">Add Note - {{ user }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% csrf_token %}
        {% crispy note_form %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input class="btn btn-primary" type="submit" value="Add Note" onclick="$(this).prop('disabled', 'disabled').val('Saving...');$('#addNoteForm').submit();">
      </div>
      </form>
    </div>
  </div>
</div>


{% endblock %}

rink/templates/roster/admin_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}


{% block title %}View Profile - {{ user }}{% endblock %}


{% block content %}

{% include 'roster/submenu.html' with submenu_selected="profile" %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    
{% crispy form %}

    </div>
</div>
{% endblock %}